# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
